# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? [], src }:

let
  sources = {
    "@fluent/bundle-0.15.1" = {
      name = "_at_fluent_slash_bundle";
      packageName = "@fluent/bundle";
      version = "0.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fluent/bundle/-/bundle-0.15.1.tgz";
        sha512 = "uhDGjpEwTMBNxYMSXyjXFBG5LY7dqoNatle6mnghu5lFOrf0JyblY/Y0al2GzDKFuYbtOSbJvUkxzjtYX3odkw==";
      };
    };
    "@protobufjs/aspromise-1.1.2" = {
      name = "_at_protobufjs_slash_aspromise";
      packageName = "@protobufjs/aspromise";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/aspromise/-/aspromise-1.1.2.tgz";
        sha1 = "9b8b0cc663d669a7d8f6f5d0893a14d348f30fbf";
      };
    };
    "@protobufjs/base64-1.1.2" = {
      name = "_at_protobufjs_slash_base64";
      packageName = "@protobufjs/base64";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/base64/-/base64-1.1.2.tgz";
        sha512 = "AZkcAA5vnN/v4PDqKyMR5lx7hZttPDgClv83E//FMNhR2TMcLUhfRUBHCmSl0oi9zMgDDqRUJkSxO3wm85+XLg==";
      };
    };
    "@protobufjs/codegen-2.0.4" = {
      name = "_at_protobufjs_slash_codegen";
      packageName = "@protobufjs/codegen";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/codegen/-/codegen-2.0.4.tgz";
        sha512 = "YyFaikqM5sH0ziFZCN3xDC7zeGaB/d0IUb9CATugHWbd1FRFwWwt4ld4OYMPWu5a3Xe01mGAULCdqhMlPl29Jg==";
      };
    };
    "@protobufjs/eventemitter-1.1.0" = {
      name = "_at_protobufjs_slash_eventemitter";
      packageName = "@protobufjs/eventemitter";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/eventemitter/-/eventemitter-1.1.0.tgz";
        sha1 = "355cbc98bafad5978f9ed095f397621f1d066b70";
      };
    };
    "@protobufjs/fetch-1.1.0" = {
      name = "_at_protobufjs_slash_fetch";
      packageName = "@protobufjs/fetch";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/fetch/-/fetch-1.1.0.tgz";
        sha1 = "ba99fb598614af65700c1619ff06d454b0d84c45";
      };
    };
    "@protobufjs/float-1.0.2" = {
      name = "_at_protobufjs_slash_float";
      packageName = "@protobufjs/float";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/float/-/float-1.0.2.tgz";
        sha1 = "5e9e1abdcb73fc0a7cb8b291df78c8cbd97b87d1";
      };
    };
    "@protobufjs/inquire-1.1.0" = {
      name = "_at_protobufjs_slash_inquire";
      packageName = "@protobufjs/inquire";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/inquire/-/inquire-1.1.0.tgz";
        sha1 = "ff200e3e7cf2429e2dcafc1140828e8cc638f089";
      };
    };
    "@protobufjs/path-1.1.2" = {
      name = "_at_protobufjs_slash_path";
      packageName = "@protobufjs/path";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/path/-/path-1.1.2.tgz";
        sha1 = "6cc2b20c5c9ad6ad0dccfd21ca7673d8d7fbf68d";
      };
    };
    "@protobufjs/pool-1.1.0" = {
      name = "_at_protobufjs_slash_pool";
      packageName = "@protobufjs/pool";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/pool/-/pool-1.1.0.tgz";
        sha1 = "09fd15f2d6d3abfa9b65bc366506d6ad7846ff54";
      };
    };
    "@protobufjs/utf8-1.1.0" = {
      name = "_at_protobufjs_slash_utf8";
      packageName = "@protobufjs/utf8";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/utf8/-/utf8-1.1.0.tgz";
        sha1 = "a777360b5b39a1a2e5106f8e858f2fd2d060c570";
      };
    };
    "@types/long-4.0.1" = {
      name = "_at_types_slash_long";
      packageName = "@types/long";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/long/-/long-4.0.1.tgz";
        sha512 = "5tXH6Bx/kNGd3MgffdmP4dy2Z+G4eaXw0SE81Tq3BNadtnMR5/ySMzX4SLEzHJzSmPNn4HIdpQsBvXMUykr58w==";
      };
    };
    "@types/node-13.13.15" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "13.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-13.13.15.tgz";
        sha512 = "kwbcs0jySLxzLsa2nWUAGOd/s21WU1jebrEdtzhsj1D4Yps1EOuyI1Qcu+FD56dL7NRNIJtDDjcqIG22NwkgLw==";
      };
    };
    "d3-array-2.4.0" = {
      name = "d3-array";
      packageName = "d3-array";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-array/-/d3-array-2.4.0.tgz";
        sha512 = "KQ41bAF2BMakf/HdKT865ALd4cgND6VcIztVQZUTt0+BH3RWy6ZYnHghVXf6NFjt2ritLr8H1T8LreAAlfiNcw==";
      };
    };
    "d3-axis-1.0.12" = {
      name = "d3-axis";
      packageName = "d3-axis";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-axis/-/d3-axis-1.0.12.tgz";
        sha512 = "ejINPfPSNdGFKEOAtnBtdkpr24c4d4jsei6Lg98mxf424ivoDP2956/5HDpIAtmHo85lqT4pruy+zEgvRUBqaQ==";
      };
    };
    "d3-color-1.4.1" = {
      name = "d3-color";
      packageName = "d3-color";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-color/-/d3-color-1.4.1.tgz";
        sha512 = "p2sTHSLCJI2QKunbGb7ocOh7DgTAn8IrLx21QRc/BSnodXM4sv6aLQlnfpvehFMLZEfBc6g9pH9SWQccFYfJ9Q==";
      };
    };
    "d3-dispatch-1.0.6" = {
      name = "d3-dispatch";
      packageName = "d3-dispatch";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-dispatch/-/d3-dispatch-1.0.6.tgz";
        sha512 = "fVjoElzjhCEy+Hbn8KygnmMS7Or0a9sI2UzGwoB7cCtvI1XpVN9GpoYlnb3xt2YV66oXYb1fLJ8GMvP4hdU1RA==";
      };
    };
    "d3-ease-1.0.6" = {
      name = "d3-ease";
      packageName = "d3-ease";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-ease/-/d3-ease-1.0.6.tgz";
        sha512 = "SZ/lVU7LRXafqp7XtIcBdxnWl8yyLpgOmzAk0mWBI9gXNzLDx5ybZgnRbH9dN/yY5tzVBqCQ9avltSnqVwessQ==";
      };
    };
    "d3-format-1.4.4" = {
      name = "d3-format";
      packageName = "d3-format";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-format/-/d3-format-1.4.4.tgz";
        sha512 = "TWks25e7t8/cqctxCmxpUuzZN11QxIA7YrMbram94zMQ0PXjE4LVIMe/f6a4+xxL8HQ3OsAFULOINQi1pE62Aw==";
      };
    };
    "d3-interpolate-1.4.0" = {
      name = "d3-interpolate";
      packageName = "d3-interpolate";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-interpolate/-/d3-interpolate-1.4.0.tgz";
        sha512 = "V9znK0zc3jOPV4VD2zZn0sDhZU3WAE2bmlxdIwwQPPzPjvyLkd8B3JUVdS1IDUFDkWZ72c9qnv1GK2ZagTZ8EA==";
      };
    };
    "d3-path-1.0.9" = {
      name = "d3-path";
      packageName = "d3-path";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-path/-/d3-path-1.0.9.tgz";
        sha512 = "VLaYcn81dtHVTjEHd8B+pbe9yHWpXKZUC87PzoFmsFrJqgFwDe/qxfp5MlfsfM1V5E/iVt0MmEbWQ7FVIXh/bg==";
      };
    };
    "d3-scale-3.2.1" = {
      name = "d3-scale";
      packageName = "d3-scale";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-scale/-/d3-scale-3.2.1.tgz";
        sha512 = "huz5byJO/6MPpz6Q8d4lg7GgSpTjIZW/l+1MQkzKfu2u8P6hjaXaStOpmyrD6ymKoW87d2QVFCKvSjLwjzx/rA==";
      };
    };
    "d3-scale-chromatic-1.5.0" = {
      name = "d3-scale-chromatic";
      packageName = "d3-scale-chromatic";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-scale-chromatic/-/d3-scale-chromatic-1.5.0.tgz";
        sha512 = "ACcL46DYImpRFMBcpk9HhtIyC7bTBR4fNOPxwVSl0LfulDAwyiHyPOTqcDG1+t5d4P9W7t/2NAuWu59aKko/cg==";
      };
    };
    "d3-selection-1.4.2" = {
      name = "d3-selection";
      packageName = "d3-selection";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-selection/-/d3-selection-1.4.2.tgz";
        sha512 = "SJ0BqYihzOjDnnlfyeHT0e30k0K1+5sR3d5fNueCNeuhZTnGw4M4o8mqJchSwgKMXCNFo+e2VTChiSJ0vYtXkg==";
      };
    };
    "d3-shape-1.3.7" = {
      name = "d3-shape";
      packageName = "d3-shape";
      version = "1.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-shape/-/d3-shape-1.3.7.tgz";
        sha512 = "EUkvKjqPFUAZyOlhY5gzCxCeI0Aep04LwIRpsZ/mLFelJiUfnK56jo5JMDSE7yyP2kLSb6LtF+S5chMk7uqPqw==";
      };
    };
    "d3-time-1.1.0" = {
      name = "d3-time";
      packageName = "d3-time";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-time/-/d3-time-1.1.0.tgz";
        sha512 = "Xh0isrZ5rPYYdqhAVk8VLnMEidhz5aP7htAADH6MfzgmmicPkTo8LhkLxci61/lCB7n7UmE3bN0leRt+qvkLxA==";
      };
    };
    "d3-time-format-2.2.3" = {
      name = "d3-time-format";
      packageName = "d3-time-format";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-time-format/-/d3-time-format-2.2.3.tgz";
        sha512 = "RAHNnD8+XvC4Zc4d2A56Uw0yJoM7bsvOlJR33bclxq399Rak/b9bhvu/InjxdWhPtkgU53JJcleJTGkNRnN6IA==";
      };
    };
    "d3-timer-1.0.10" = {
      name = "d3-timer";
      packageName = "d3-timer";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-timer/-/d3-timer-1.0.10.tgz";
        sha512 = "B1JDm0XDaQC+uvo4DT79H0XmBskgS3l6Ve+1SBCfxgmtIb1AVrPIoqd+nPSv+loMX8szQ0sVUhGngL7D5QPiXw==";
      };
    };
    "d3-transition-1.3.2" = {
      name = "d3-transition";
      packageName = "d3-transition";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-transition/-/d3-transition-1.3.2.tgz";
        sha512 = "sc0gRU4PFqZ47lPVHloMn9tlPcv8jxgOQg+0zjhfZXMQuvppjG6YuwdMBE0TuqCZjeJkLecku/l9R0JPcRhaDA==";
      };
    };
    "intl-pluralrules-1.2.0" = {
      name = "intl-pluralrules";
      packageName = "intl-pluralrules";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/intl-pluralrules/-/intl-pluralrules-1.2.0.tgz";
        sha512 = "7v29fFKsaPquXezxttUNFdE6LQUD41I8JX76royEWBPuYIEruvfvprU3d8CsiNVIieVg/VeV2ee5WI0w0Vs2Sg==";
      };
    };
    "lodash.debounce-4.0.8" = {
      name = "lodash.debounce";
      packageName = "lodash.debounce";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.debounce/-/lodash.debounce-4.0.8.tgz";
        sha1 = "82d79bff30a67c4005ffd5e2515300ad9ca4d7af";
      };
    };
    "lodash.throttle-4.1.1" = {
      name = "lodash.throttle";
      packageName = "lodash.throttle";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.throttle/-/lodash.throttle-4.1.1.tgz";
        sha1 = "c23e91b710242ac70c37f1e1cda9274cc39bf2f4";
      };
    };
    "long-4.0.0" = {
      name = "long";
      packageName = "long";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/long/-/long-4.0.0.tgz";
        sha512 = "XsP+KhQif4bjX1kbuSiySJFNAehNxgLb6hPRGJ9QsUr8ajHkuXGdrHmFUTUUXhDwVX2R5bY4JNZEwbUiMhV+MA==";
      };
    };
    "protobufjs-6.10.1" = {
      name = "protobufjs";
      packageName = "protobufjs";
      version = "6.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/protobufjs/-/protobufjs-6.10.1.tgz";
        sha512 = "pb8kTchL+1Ceg4lFd5XUpK8PdWacbvV5SK2ULH2ebrYtl4GjJmS24m6CKME67jzV53tbJxHlnNOSqQHbTsR9JQ==";
      };
    };
  };
  args = {
    name = "anki";
    packageName = "anki";
    version = "0.1.0";
    inherit src;
    dependencies = [
      sources."@fluent/bundle-0.15.1"
      sources."@protobufjs/aspromise-1.1.2"
      sources."@protobufjs/base64-1.1.2"
      sources."@protobufjs/codegen-2.0.4"
      sources."@protobufjs/eventemitter-1.1.0"
      sources."@protobufjs/fetch-1.1.0"
      sources."@protobufjs/float-1.0.2"
      sources."@protobufjs/inquire-1.1.0"
      sources."@protobufjs/path-1.1.2"
      sources."@protobufjs/pool-1.1.0"
      sources."@protobufjs/utf8-1.1.0"
      sources."@types/long-4.0.1"
      sources."@types/node-13.13.15"
      sources."d3-array-2.4.0"
      sources."d3-axis-1.0.12"
      sources."d3-color-1.4.1"
      sources."d3-dispatch-1.0.6"
      sources."d3-ease-1.0.6"
      sources."d3-format-1.4.4"
      sources."d3-interpolate-1.4.0"
      sources."d3-path-1.0.9"
      sources."d3-scale-3.2.1"
      sources."d3-scale-chromatic-1.5.0"
      sources."d3-selection-1.4.2"
      sources."d3-shape-1.3.7"
      sources."d3-time-1.1.0"
      sources."d3-time-format-2.2.3"
      sources."d3-timer-1.0.10"
      sources."d3-transition-1.3.2"
      sources."intl-pluralrules-1.2.0"
      sources."lodash.debounce-4.0.8"
      sources."lodash.throttle-4.1.1"
      sources."long-4.0.0"
      sources."protobufjs-6.10.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Anki JS support files";
      license = "AGPL-3.0-or-later";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
